# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-01 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hash_base_id', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'hashes',
            },
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=320, null=True)),
            ],
            options={
                'db_table': 'blacklist',
            },
        ),
        migrations.CreateModel(
            name='DeletedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zone', models.CharField(max_length=100)),
                ('name_redemption', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('email', models.CharField(blank=True, max_length=320, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'delete_info',
            },
        ),
        migrations.CreateModel(
            name='DomainException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=320, null=True)),
                ('name_zone', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'emails',
            },
        ),
        migrations.CreateModel(
            name='EventLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('action', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('number_of_redemption', models.IntegerField(default=0)),
                ('number_of_all', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('number_act', models.IntegerField(default=0)),
                ('number_act_2', models.IntegerField(default=0)),
                ('number_sent', models.IntegerField(default=0)),
                ('number_sent_2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=320, null=True)),
                ('name_redemption', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'process_tracker',
            },
        ),
        migrations.CreateModel(
            name='RawLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zone', models.CharField(max_length=100)),
                ('name_redemption', models.CharField(max_length=100)),
                ('mail', models.CharField(blank=True, max_length=320, null=True)),
                ('page', models.SmallIntegerField(default=1)),
                ('activated', models.SmallIntegerField(default=0)),
                ('mark', models.SmallIntegerField(default=0)),
                ('mark_to_send', models.SmallIntegerField(default=0)),
                ('to_delete', models.SmallIntegerField(default=0)),
                ('blacklist', models.SmallIntegerField(default=0)),
                ('no_email_found', models.SmallIntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hash_base_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('reminder', models.SmallIntegerField(default=0)),
                ('last_email_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'raw_leads',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days', models.IntegerField(default=5)),
                ('com_net', models.SmallIntegerField(default=2)),
                ('length', models.SmallIntegerField(default=60)),
                ('number_of_digits', models.SmallIntegerField(default=0)),
                ('number_of_keywords', models.SmallIntegerField(default=3)),
                ('allow_bad_keywords', models.SmallIntegerField(default=1)),
                ('min_length', models.SmallIntegerField(default=4)),
                ('max_length', models.SmallIntegerField(default=11)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='SuperBlacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'super_blacklist',
            },
        ),
    ]
