# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-06 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zone', models.CharField(max_length=100)),
                ('name_redemption', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'raw_leads',
            },
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
