# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-24 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tlds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=10)),
            ],
        ),
    ]
