# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-26 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_tlds'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoisAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.IntegerField(default=0)),
                ('succeeded', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'whois_analytics',
            },
        ),
    ]
