# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-12 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_rawleads_send_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawleads',
            name='mail',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
