# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-12 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_rawleads_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawleads',
            name='sent',
            field=models.SmallIntegerField(default=0),
        ),
    ]
