# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-12 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_rawleads_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawleads',
            name='mail',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
