# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-12 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_rawleads_sent'),
        ('domain', '0005_auto_20161112_1817'),
    ]

    operations = [
    ]
