# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-26 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_whoisanalytics_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='redempion_row',
            field=models.SmallIntegerField(default=1),
        ),
    ]
