# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-26 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_setting_redempion_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='vpn_count',
            field=models.SmallIntegerField(default=1),
        ),
    ]
