# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-14 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.CharField(default=None, max_length=100)),
                ('sent', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'zone_domains',
            },
        ),
        migrations.AlterField(
            model_name='rawleads',
            name='mail',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
