# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-26 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0007_setting_vpn_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'zone_domains',
            },
        ),
    ]
