# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-14 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0007_auto_20161114_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonedomains',
            name='mail',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
