# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_auto_20161114_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawleads',
            name='archive',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawleads',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rawleads',
            name='return_or_delete',
            field=models.SmallIntegerField(default=0),
        ),
    ]
