# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-27 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_zonedomains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonedomains',
            name='domain',
            field=models.CharField(max_length=100),
        ),
    ]
