# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0009_auto_20161117_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawleads',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
