# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-27 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0009_auto_20170527_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonedomains',
            name='domain',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
