# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-19 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0010_auto_20161117_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawleads',
            name='blacklist',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawleads',
            name='mark_to_send',
            field=models.SmallIntegerField(default=0),
        ),
    ]
