# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-20 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0011_auto_20161119_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.CharField(max_length=100)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('base_id', models.IntegerField()),
                ('hash_base_id', models.CharField(max_length=32, unique=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('response', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'ponude',
            },
        ),
        migrations.DeleteModel(
            name='ZoneDomains',
        ),
    ]
