# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-02 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0011_auto_20170602_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
