# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-06 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0012_auto_20170602_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawleads',
            name='list_no',
            field=models.SmallIntegerField(default=1),
        ),
    ]
