# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-20 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0012_auto_20161120_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
