# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-20 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0013_offer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
