# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-20 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0014_offer_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='date_resp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
