# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-24 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0015_offer_date_resp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawleads',
            name='to_archive',
            field=models.SmallIntegerField(default=0),
        ),
    ]
