# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-26 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0017_rawleads_to_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
