# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-26 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0018_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
