# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-26 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0019_auto_20161126_1420'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='offer',
            table='offers',
        ),
    ]
