# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-26 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0020_auto_20161126_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'blacklist',
            },
        ),
    ]
