# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-30 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0021_blacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('number_of_redemption', models.IntegerField(default=0)),
                ('number_of_all', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='rawleads',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='rawleads',
            name='return_or_delete',
        ),
        migrations.RemoveField(
            model_name='rawleads',
            name='send_mail',
        ),
        migrations.RemoveField(
            model_name='rawleads',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='rawleads',
            name='to_archive',
        ),
        migrations.AddField(
            model_name='rawleads',
            name='activated',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawleads',
            name='mark',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawleads',
            name='page',
            field=models.SmallIntegerField(default=1),
        ),
    ]
