# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-05 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0022_auto_20161130_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='email',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='rawleads',
            name='mail',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
