# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-16 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0024_auto_20161210_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_base_id', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'hashes',
            },
        ),
    ]
