# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-03 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0025_allhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawleads',
            name='hash_base_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
