# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-03 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0026_rawleads_hash_base_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=320, null=True)),
                ('name_zone', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'emails',
            },
        ),
    ]
