# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-16 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0027_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='number_act',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='number_sent',
            field=models.IntegerField(default=0),
        ),
    ]
