# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-16 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0028_auto_20170216_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='number_act_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='number_sent_2',
            field=models.IntegerField(default=0),
        ),
    ]
