# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-21 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0029_auto_20170216_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days', models.IntegerField(default=5)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
