# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-22 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0030_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawleads',
            name='no_email_found',
            field=models.SmallIntegerField(default=0),
        ),
    ]
