# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-02 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0032_processtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawleads',
            name='reminder',
            field=models.SmallIntegerField(default=0),
        ),
    ]
