# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0033_rawleads_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawleads',
            name='last_email_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
