# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-11 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0035_deletedinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='allow_bad_keywords',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='setting',
            name='com_net',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='setting',
            name='length',
            field=models.SmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='setting',
            name='max_length',
            field=models.SmallIntegerField(default=11),
        ),
        migrations.AddField(
            model_name='setting',
            name='min_length',
            field=models.SmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='setting',
            name='number_of_digits',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setting',
            name='number_of_keywords',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='deletedinfo',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
