# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-14 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0037_eventlogger'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventlogger',
            table=None,
        ),
    ]
