# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0037_eventlogger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlogger',
            name='action',
            field=models.CharField(max_length=10000),
        ),
    ]
