# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-20 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0039_domainexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='allhash',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
