# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-04 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0040_allhash_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedinfo',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='processtracker',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
